### PR TITLE
Change return value of rqa to named Tuple

### LINKED ISSUE #59: Return Type of rqa()
Why is the return type of rqa a Dict?
With a NamedTuple you still have the clear connection between the values and the name of the metric.
Furthermore, the return values are ordered, and it is a little bit cheaper because it needs less allocations.
See https://discourse.julialang.org/t/namedtuples-vs-dict/13119
I made some tests with NamedTuples, with the code on my branch. 
For a 100 x 100 RecurrenceMatrix the number of allocations is reduced from 257 to 209 and the running time is reduced from 112,5  microseconds to 107,8 microseconds. 
For me this is important, because I want to apply rqa on a large number of pixels (at least a million) with around 100 timesteps.

### PR DESCRIPTION
**Pull request by felixcremer**
This should be faster than using a Dict.
This would close #59

### CODE REVIEW

**Comment by Datseris** [comment]
Could you please modify the documentation string? The return type is not a dictionary anymore and the keys are not strings. You can change e.g. `"RR"` to be surrounded by ticks instead of quotes (" -> `).

We also have to modify all test files since now we can't access `rqa_params` with `["RR"]` but with `.RR` instead (or with `[:RR]`)

**Comment by felixcremer** [comment]
I will change the docstring and the tests tomorrow morning. 
Do we also need to change something in windowed.jl to make the return type consistent?
If so, I think I would need your assistance, because I don't understand the macro code.

**Comment by Datseris** [comment]
Perfect, thanks!

> If so, I think I would need your assistance, because I don't understand the macro code.

Huhu, me neither :D 

Don't worry, I am sure @heliosdrm can take care of any change that needs to be done in the `@windowed` code.

**Comment by heliosdrm** [comment]
Ok, I'll do it tomorrow

**Comment by felixcremer** [comment]
@heliosdrm  Could you have a look at the changes I did in  windowed.jl. 
It is now returning a NamedTuple of vectors. 
I am now changing the tests.

**Pull request merged**
