### PR TITLE
Update compat bounds of dependencies and tests

### PR DESCRIPTION
**Pull request by heliosdrm**
Fix depwarn of Distances v0.8, cf. #83

### CODE REVIEW

**Comment by heliosdrm** [comment]
Do not merge yet, there is something failing...

**Comment by Datseris** [comment]
This should also add a compat entry of `Distances = 0.8` then, right?

**Comment by heliosdrm** [comment]
You're right. It's also updated.

By the way, maybe we should also modify the `Project.toml` in order to specify upper bounds to all compats (including Julia), following the recommended policy of the General Registry...

I'l file an issue about that.

**Comment by Datseris** [comment]
> By the way, maybe we should 

Yeap I have done this in the other repo's, we should do it here as well. In fact, this PR is a good idea to do it in.

**Comment by heliosdrm** [comment]
Ok, I have changed the title of the PR and will add here the commits for Project.toml

**Comment by heliosdrm** [comment]
Also added tests for OSX and Windows in Travis, but if you think that this makes testing too heavy, it can be removed.

**Comment by heliosdrm** [comment]
Julia 0.7 is not happy with the current code. Shall we drop 0.7 support?

**Comment by Datseris** [comment]
> Julia 0.7 is not happy with the current code. Shall we drop 0.7 support?

Yeap go ahead! You can also remove AppVeyor, we now test windows on travis anyway!

**Pull request merged**
