### PR TITLE
Parallelize recurrence matrix construction

### LINKED ISSUE #76: Performance of computation of recurrence matrices
Initially asked by @asinghvi17 , is it possible to parallelize or put on the GPU the calculation of Recurrence matrices? I have no knowledge on the GPU, so I will only talk about parallelization. The core function that does the number crunching is:

```julia
function _recurrence_matrix(xx::Dataset, yy::Dataset, ε, metric::Metric)
    x = xx.data
    y = yy.data
    rowvals = Vector{Int}()
    colvals = Vector{Int}()
    for j in 1:length(y)
        nzcol = 0
        for i in 1:length(x)
            @inbounds if evaluate(metric, x[i], y[j]) ≤ ε
                push!(rowvals, i)
                nzcol += 1
            end
        end
        append!(colvals, fill(j, (nzcol,)))
    end
    nzvals = fill(true, (length(rowvals),))
    return sparse(rowvals, colvals, nzvals, length(x), length(y))
end
```
You can see that the algorithm operates via `push!` instead of pre-allocating. It may be a tiny bit trick, but I don't think it should be impossible to parallelize this.

@heliosdrm do you have any take on this?

### PR DESCRIPTION
**Pull request by asinghvi17**
Adds a kwarg to `_recurrence_matrix`, which controls whether the 
parallel or serial algorithm is called.

Partially fixes #76

### CODE REVIEW

**Comment by Datseris** [comment]
@asinghvi17 I am sorry, but could you please wait to progress with this after I do #77 ? I will be simplifing the `recurrencematrix` interface there. And then this may also need less work to be done.

**Comment by asinghvi17** [comment]
It's pretty much done,  just needs the parallelization heuristic.

**Comment by Datseris** [comment]
Hi @asinghvi17 , can you please adapt this based on #82 ?

**Comment by asinghvi17** [comment]
Will look into it today.

**Comment by Datseris** [comment]
Oh Cool! SORRY i forgot about this!

**Pull request closed without merging**
